--- #YAML:1.0
name:               constant-override
version:            0.01
abstract:           Override/ignore constants
author:
    - Tom Harrison <cpan@apnic.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sub::Uplevel:  0
    Test::More:    0.90
    Test::Pod:     0.95
resources:
    repository:  https://github.com/APNIC-net/p5-constant-override
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
